package World;

public class Hero {
    static void testNull()throws MyException{
        int num=120;
        while((num>=-128)&&(num<127))
            num++;
        if((num<-128)||(num>=127)){
            throw new MyException("超出Integer范围了");
        }
    }
    public static void main(String []args){
        try {
            testNull();
        } catch (MyException e) {
            System.out.println("testNull()中抛出的异常是"+e);
        }
    }
}